
---
- hosts: webservers
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Loome public_html kataloogi user'ile
      file:
       path=/home/kivi/public_html
       owner=kivi
       group=kivi
       mode=0755
       state=directory

    - name: Lubame userdir mod
      apache2_module: name=userdir state=present

    - name: Apache2 serverile alglaadimine(restart)
      service:
        name: apache2
        state: restarted

    - name: Kopeerime index.html fail USER_ile kodus_public_html kataloogi
      copy:
        src: /var/www/html/index.html
        dest: /home/kivi/public_html/
        remote_src: yes
        owner: kivi
        group: kivi

    - name: user index.html redigeerimine
      lineinfile: dest=/home/kivi/public_html/index.html regexp="Apache2 Debian Default Page" line="Kivi legekülg" state=present

    - name: Apache2 serverile alglaadimine(restart)
      service:
        name: apache2
        state: restarted

